spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true
    clean-disabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/propsdb
    username: postgres
    password: Viktor1032003
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    show-sql: true
  web:
    resources:
      add-mappings: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  server:
    max-http-header-size: 16KB
    tomcat:
      max-swallow-size: -1
      max-http-header-size: 16KB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days